services:
  # Backend API Service
  - type: web
    name: docmindai-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/main.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 8000

  # Frontend Flask Service
  - type: web
    name: docmindai-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn frontend.app:app --timeout 120 --bind 0.0.0.0:5000
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: API_URL
        value: https://docmindai-backend.onrender.com
      - key: PORT
        value: 5000 