services:
  # Backend API Service
  - type: web
    name: documind-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/main.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 8000

  # Frontend Flask Service
  - type: web
    name: documind-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python frontend/app.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: API_URL
        value: https://documind-backend.onrender.com
      - key: PORT
        value: 5000 