services:
  # Backend API Service
  - type: web
    name: documind-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: GROQ_API_KEY
        sync: false

  # Frontend Streamlit Service
  - type: web
    name: documind-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd frontend && streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: API_URL
        value: https://documind-backend.onrender.com 