services:
  - type: web
    name: docmind-backend
    env: docker
    rootDir: backend
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: USE_PINECONE
        value: "false"
      - key: EMBEDDING_PROVIDER
        value: openai
      - key: HF_API_TOKEN
        sync: false
      - key: HF_EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: docmindai
      - key: PINECONE_HOST
        value: ""
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: docmind-frontend
    env: docker
    rootDir: frontend
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      # Set API_URL to the backend's internal URL on Render
      - key: API_URL
        fromService:
          type: web
          name: docmind-backend
          envVarKey: RENDER_EXTERNAL_URL


